<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0;netstandard2.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>JJConsulting.Html.Bootstrap offers a strongly typed way to create Bootstrap components.</Description>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
      <PackageReference Include="JJConsulting.FontAwesome" Version="1.0.0" />
      <PackageReference Include="PolySharp" Version="1.15.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JJConsulting.Html\JJConsulting.Html.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="JetBrains.Annotations"/>
    </ItemGroup>
</Project>
