<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>JJConsulting.Html.Bootstrap.TagHelpers provides a strongly typed set of Bootstrap-aligned Tag Helpers that enable clean, declarative component usage directly within Razor views.</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\JJConsulting.Html.Bootstrap\JJConsulting.Html.Bootstrap.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
