<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <Description>JJMasterData library to render JJMasterData's components.</Description>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
    </ItemGroup>

</Project>
